# Site settings
title: Latest Swift
header-img: img/home-bg.jpg
email: developers.stepup@gmail.com
copyright_name: Step Up Apps
description: "Discuss swift related articles and questions."
baseurl: ""
url: "https://stepupapps.github.io"
twitter_username: appstepup
github_username:  github
facebook_username:  github
email_username:  developers.stepup@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
